spring:
  profiles:
    active: dev
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin

logging:
  level:
    org:
      springframework:
        data:
          r2dbc: DEBUG